client_config_backend: file
client_config:
    client_id: 771069616627-o62kfjmf7u9evlgdereg0qdv04h5205r.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive